{{- if .Values.rbac.create }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.namespace }}-admins-role
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["*"]
  verbs: ["*"]
 
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.namespace }}-admins-rolebinding
  namespace: {{ .Values.namespace }}
subjects:
- kind: Group
  name: {{ .Values.namespace }}-admins
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{ .Values.namespace }}-admins-role
  apiGroup: rbac.authorization.k8s.io

{{- end -}}