apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.namespace }}-resource-quota
spec:
  hard:
    requests.cpu: {{ .Values.quotas.cpu }}
    requests.memory: {{ .Values.quotas.memory }}
    limits.cpu: {{ .Values.quotas.cpu }}
    limits.memory: {{ .Values.quotas.memory }}