{{- if .Values.fargate -}}
apiVersion: upc.tfp.eks/v1alpha1
kind: FargateProfile
metadata:
  name: {{ .Values.namespace }}
spec:
  parameters:
    namespace: "{{ .Values.namespace }}"
    env: "{{ .Values.environment }}"
  compositionRef:
    name: fargate-profile-platform
{{- end }}